name: Dart/Flutter Package Analyzer
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.commit_secret}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dart/Flutter Package Analyzer
        # You may pin to the exact commit or the version.
        # uses: axel-op/dart-package-analyzer@7a6c3c66bce78d82b729a1ffef2d9458fde6c8d2
        uses: axel-op/dart-package-analyzer@v3
        with:
          # Token to connect to GitHub. Use secrets.GITHUB_TOKEN
          githubToken: secrets.GITHUB_TOKEN
          # Path of the package relatively to the root of the repository
          relativePath: ./lib/
